/********1*********2*********3*********4*********5**********6*********7*********/
/*                                                                             */
/*  PRODUCT      : MAD Device Simulation Framework                             */
/*  COPYRIGHT    : (c) 2022 HTF Consulting                                     */
/*                                                                             */
/* This source code is provided by exclusive license for non-commercial use to */
/* XYZ Company                                                                 */
/*                                                                             */
/*******************************************************************************/
/*                                                                             */
/*  Exe file ID  : MadSimUI.exe                                                */
/*                                                                             */
/*  Module  NAME : About.h                                                     */
/*                                                                             */
/*  DESCRIPTION  : Read Registry functions for any Functional device driver    */
/*                 working with a simulation                                   */
/*                 Derived from WDK-Toaster\bus\bus.c                           */
/*                                                                             */
/*******************************************************************************/

void doAbout(void);
