/********1*********2*********3*********4*********5**********6*********7*********/
/*                                                                             */
/*  PRODUCT      : MAD Device Simulation Framework                             */
/*  COPYRIGHT    : (c) 2022 HTF Consulting                                     */
/*                                                                             */
/* This source code is provided by exclusive license for non-commercial use to */
/* XYZ Company                                                                 */
/*                                                                             */
/*******************************************************************************/
/*                                                                             */
/*  Exe file ID  : MadSimUI.exe                                                */
/*                                                                             */
/*  Module  NAME : Help.h                                                      */
/*                                                                             */
/*  DESCRIPTION  : Definitons of the help resource ids                         */
/*                                                                             */
/*******************************************************************************/

#define HID_SETUP_DIALOG 1003
#define HID_INTERRUPT_MGT 1020
