//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MadDevSimUsrInt.rc
//
#define IDC_SETUP_HELP                  3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SIMULATOR_DIALOG            102
#define IDS_PROGRAM_ROOT                102
#define IDS_IRQ                         103
#define IDS_SEND                        104
#define IDS_SEND_NEXT                   105
#define IDS_OPEN_FAILED                 106
#define IDS_POLLING_INTERVAL            107
#define IDS_FILE_OPEN_FAILED            108
#define IDS_FILE_SAVE                   109
#define IDS_FILE_SAVE_AS                110
#define IDS_FILTER                      111
#define IDS_DEVICEIO_FAILED_READ        112
#define IDS_WRONG_LENGTH_READ           113
#define IDS_DEVICEIO_FAILED_WRITE       114
#define IDS_DEVICEIO_FAILED_SET_INTR    115
#define IDS_DEVICEIO_FAILED_GEN         116
#define IDS_GODONEMIN                   117
#define IDS_GODONEVAR                   118
#define IDS_STOP_TIMEOUT                119
#define IDS_STOP_ERROR                  120
#define IDS_ERROR_INJECTED              121
#define IDS_PROB_LOST                   122
#define IDS_PROB_SPURIOUS               123
#define IDS_PROB_ERR                    124
#define IDS_PROB_OVR_UND                125
#define IDS_DEVICEIO_FAILED_SET_TRACE   126
#define IDS_DEVICEIO_FAILED_GET_TRACE   127
#define IDR_MAINFRAME                   128
#define IDR_ACCELERATOR                 129
#define IDD_SETUP                       130
#define IDI_JMNCO                       130
#define IDB_TEC                         131
#define IDD_INTERRUPTS                  132
#define IDD_IntErrors                   132
#define IDR_MAINMENU                    133
#define IDI_ICON1                       134
#define IDD_COMMENT                     135
#define IDD_HDWTRACE                    136
#define IDD_REGISTERS                   137
#define IDD_PacketTermination           138
#define IDS_PROB_TIMEOUT                139
#define IDD_AllocMemory                 139
#define IDD_DeallocMemory               140
#define IDD_InheritedDlg                141
#define IDS_PROB_BUSY                   142
#define IDC_TRACE                       1000
#define IDS_ITEM_UNKNOWN                1000
#define IDC_GO_OUT                      1002
#define IDC_DONE_IN                     1003
#define IDC_DATA                        1004
#define IDC_SEND                        1005
#define IDC_ExeManual                   1006
#define IDC_FREERUN                     1007
#define IDC_SemiAuto                    1007
#define IDC_BURSTINPUT                  1007
#define IDC_ExeBurst                    1007
#define IDC_EOP_IN                      1008
#define IDC_CLEAR                       1009
#define IDC_GENERATE                    1010
#define IDC_SETUP                       1011
#define IDC_INT_IN                      1012
#define IDC_IRQ                         1013
#define IDC_OVR_IN                      1013
#define IDC_IE_IN                       1014
#define IDC_ERR_IN                      1015
#define IDC_DONE_OUT                    1016
#define IDC_BUSY_OUT                    1017
#define IDC_INT_OUT                     1018
#define IDC_UND_OUT                     1019
#define IDC_ERR_OUT                     1020
#define IDC_IE_OUT                      1021
#define IDC_ERRORS                      1022
#define IDC_GENL_ERRORS                 1022
#define IDC_GO_IN                       1023
#define IDC_OVRUND                      1024
#define IDC_OVRUND_ERRS                 1024
#define IDC_INT                         1025
#define IDC_ERROR                       1026
#define IDC_TRANSFER                    1027
#define IDC_XTRA_INTS                   1028
#define IDC_LOSE                        1029
#define IDC_IACK_IN                     1029
#define IDC_SPURIOUS                    1030
#define IDC_IACK_OUT                    1030
#define IDC_BOTH                        1031
#define IDC_RST_IN                      1031
#define IDC_PLOSE                       1032
#define IDC_RST_OUT                     1032
#define IDC_PSPURIOUS                   1033
#define IDC_SPINLOSE                    1034
#define IDC_SPINSPURIOUS                1035
#define IDC_PERR                        1036
#define IDC_SPINPERR                    1037
#define IDC_POVR                        1038
#define IDC_SPINPOVR                    1039
#define IDC_PERR_CAPTION                1040
#define IDC_HELP_COMMAND                1041
#define IDC_CANCEL                      1041
#define IDC_GO_HACK_IN                  1042
#define IDC_GO_HACK_OUT                 1043
#define IDC_POLLINTERVAL                1043
#define IDC_SPINPOLLINTERVAL            1044
#define IDC_CLOSE                       1045
#define IDC_GODONE_MIN                  1045
#define IDC_SPINGODONEMIN               1046
#define IDC_COMMENT                     1046
#define IDC_GODONE_VAR                  1047
#define IDC_SPINGODONEVAR               1048
#define IDC_SINGLESTEP                  1049
#define IDC_ExeSnglStep                 1049
#define IDC_GETSTATE                    1050
#define IDC_GETIOSTATE                  1050
#define IDC_IOCTLS                      1051
#define IDC_TRC_IOCTLS                  1051
#define IDC_REGS                        1052
#define IDC_IN_COMMAND                  1052
#define IDC_TRC_REGS                    1052
#define IDC_RD_CONTROL                  1052
#define IDC_IN_STATUS                   1053
#define IDC_Data2Device                 1053
#define IDC_RD_STATUS                   1053
#define IDC_IN_DATA                     1054
#define IDC_MaxLen                      1054
#define IDC_IN_LEN                      1054
#define IDC_RD_INT_ACTV                 1054
#define IDC_OUT_COMMAND                 1055
#define IDC_TermChar                    1055
#define IDC_RD_INT_ID                   1055
#define IDC_OUT_STATUS                  1056
#define IDC_GetOutState                 1056
#define IDC_RD_IN_LEN                   1056
#define IDC_OUT_DATA                    1057
#define IDC_GetInpState                 1057
#define IDC_OUT_LEN                     1057
#define IDC_RD_OUT_LEN                  1057
#define IDC_AutoInput                   1058
#define IDC_ExeAutoIn                   1058
#define IDC_AutoOutput                  1059
#define IDC_ExeAutoOut                  1059
#define IDC_CHECK_IntTmOuts             1062
#define IDC_Stc_ProbTimeout             1067
#define IDC_PROB_DEVBUSY                1067
#define IDC_ProbTimOut                  1068
#define IDC_SPIN_PROBTIMEOUT            1069
#define IDC_DA_Shared                   1070
#define IDC_DA_Contig                   1071
#define IDC_DA_Locked                   1072
#define IDC_DA_Paged                    1073
#define IDC_Numpages                    1074
#define IDC_Stc_NumPages                1075
#define IDC_Locked                      1076
#define IDC_Shared                      1077
#define IDC_Contig                      1078
#define IDC_DA_DmaOut                   1080
#define IDC_DA_DmaIn                    1081
#define IDC_DmaOut                      1082
#define IDC_DmaIn                       1083
#define IDC_IN_DMAHI                    1084
#define IDC_RD_IN_DMAHI                 1084
#define IDC_IN_DMALO                    1085
#define IDC_RD_IN_DMALO                 1085
#define IDC_OUT_DMAHI                   1086
#define IDC_RD_OUT_DMAHI                1086
#define IDC_OUT_DMALO                   1087
#define IDC_RD_OUT_DMALO                1087
#define IDC_AutoDuplex                  1088
#define IDC_ExeAutoFull                 1088
#define IDC_TRC_INTS                    1089
#define IDC_DEVBUSYERRS                 1090
#define IDC_DEVBUSY_ERRS                1090
#define IDC_RADIO1                      1091
#define IDC_IntErrNone                  1091
#define IDC_RandomPkts                  1092
#define IDC_POWER_STATE                 1093
#define IDC_RD_POWER_STATE              1093
#define IDC_RD_MESGID                   1094
#define IDC_RD_DATA1                    1094
#define IDC_RD_DATA2                    1095
#define IDC_RD_DATA3                    1096
#define IDC_CNTL_14                     1098
#define IDC_STATIC_CntlDash             1099
#define IDC_STATIC_RegBits              1100
#define IDC_EDIT1                       1101
#define IDC_MesgID                      1101
#define IDC_STAT_12                     1116
#define IDC_STAT_11                     1117
#define IDC_STAT_10                     1118
#define IDC_STAT_09                     1119
#define IDC_STAT_08                     1120
#define IDC_STAT_07                     1121
#define IDC_STAT_06                     1122
#define IDC_STAT_05                     1123
#define IDC_STAT_04                     1124
#define IDC_STAT_03                     1125
#define IDC_STAT_02                     1126
#define IDC_STAT_01                     1127
#define IDC_STAT_00                     1128
#define IDC_INTEN_15                    1129
#define IDC_INTEN_14                    1130
#define IDC_INTEN_13                    1131
#define IDC_INTEN_12                    1132
#define IDC_INTEN_11                    1133
#define IDC_INTEN_10                    1134
#define IDC_INTEN_09                    1135
#define IDC_INTEN_08                    1136
#define IDC_INTEN_07                    1137
#define IDC_INTEN_06                    1138
#define IDC_INTEN_05                    1139
#define IDC_INTEN_04                    1140
#define IDC_INTEN_03                    1141
#define IDC_INTEN_02                    1142
#define IDC_INTEN_01                    1143
#define IDC_INTEN_00                    1144
#define IDC_INTID_15                    1146
#define IDC_INTID_14                    1147
#define IDC_INTID_13                    1148
#define IDC_INTID_12                    1149
#define IDC_INTID_11                    1150
#define IDC_INTID_10                    1151
#define IDC_INTID_09                    1152
#define IDC_INTID_08                    1153
#define IDC_INTID_07                    1154
#define IDC_INTID_06                    1155
#define IDC_INTID_05                    1156
#define IDC_INTID_04                    1157
#define IDC_INTID_03                    1158
#define IDC_INTID_02                    1159
#define IDC_INTID_01                    1160
#define IDC_INTID_00                    1161
#define IDC_CNTL_15                     1162
#define IDC_CNTL_13                     1164
#define IDC_CNTL_12                     1165
#define IDC_CNTL_11                     1166
#define IDC_CNTL_10                     1167
#define IDC_CNTL_09                     1168
#define IDC_CNTL_08                     1169
#define IDC_CNTL_07                     1170
#define IDC_CNTL_06                     1171
#define IDC_CNTL_05                     1172
#define IDC_CNTL_04                     1173
#define IDC_CNTL_03                     1174
#define IDC_CNTL_02                     1175
#define IDC_CNTL_01                     1176
#define IDC_CNTL_00                     1177
#define IDC_STAT_15                     1178
#define IDC_STAT_14                     1179
#define IDC_STAT_13                     1180
#define ID_FILE_EXIT                    32771
#define ID_SETUP_IRQ                    32772
#define IDM_INTERRUPT_MGT               32773
#define IDM_SETUP_IRQ                   32774
#define IDC_DEBUG                       32775
#define IDC_CLEAR_INPUT                 32776
#define IDM_DEBUG                       32777
#define IDM_HDWSIM_TRACE                32778
#define IDM_REG_DISP                    32779
#define ID_SETUP_PACKETTERMINATION      32780
#define IDC_CLEAR_OUTPUT                32781
#define ID_SETUP_OUTPUTDISPLAY          32782
#define ID_VIEW_OUTPUTDISPLAY           32783
#define ID_VIEW_REGISTERS               32784
#define ID_VIEW_ABSTRACTDEVICEDRIVERTRACE 32785
#define ID_VIEW_DETAILEDINTERNALTRACE   32786
#define ID_VIEW_BINARYDATA              32787
#define ID_WINDOW_CLEARGENERATE         32788
#define ID_RESET_IOwPower               32791
#define ID_RESET_Init_MAD_Drivr         32792
#define ID_FILE_OPENABSTRACTDEVICE      32793
#define ID_FILE_SAVEDEVICEOUTPUT        32794
#define ID_FILE_SAVETRACE_SAVE          32795
#define ID_FILE_SAVETRACE_SAVEAS        32796
#define ID_FILE_AUTOSAVE                32800
#define ID_VIEW_INTERNALTRACE           32801
#define ID_RESET_PLAYDEAD               32802
#define ID_FILE_SAVE_DEVICEDATA         32803
#define ID_FILE_RETRIEVE_DEVICEDATA     32804
#define ID_FILE_MAPDEVICEREGISTERS      32805

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32806
#define _APS_NEXT_MAD_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
