/********1*********2*********3*********4*********5**********6*********7*********/
/*                                                                             */
/*  PRODUCT      : MAD Device Simulation Framework                             */
/*  COPYRIGHT    : (c) 2022 HTF Consulting                                     */
/*                                                                             */
/* This source code is provided by exclusive license for non-commercial use to */
/* XYZ Company                                                                 */
/*                                                                             */
/*******************************************************************************/
/*                                                                             */
/*  Exe file ID  : MadSimUI.exe                                                */
/*                                                                             */
/*  Module  NAME : UWM.h                                                       */
/*                                                                             */
/*  DESCRIPTION  : Windows Message IDs.                                        */
/*                                                                             */
/*******************************************************************************/

extern UINT UWM_UPDATE_CONTROLS;
extern UINT UWM_PULSE;
extern UINT UWM_ACQUIRE_SPINLOCK;
extern UINT UWM_RELEASE_SPINLOCK;
extern UINT UWM_OPEN_FAILED;
extern UINT UWM_IMGR_CLOSE;
extern UINT UWM_REG_CLOSE;
extern UINT UWM_POLL;
extern UINT UWM_SET_TIMER_OUT;
extern UINT UWM_SET_TIMER_IN;
extern UINT UWM_GO_HACK_IN;
extern UINT UWM_GO_HACK_OUT;
extern UINT UWM_SET_MANUAL_MODE;
extern UINT UWM_GEN_RANDOM_PKTS;
extern UINT UWM_SET_PROB;
extern UINT UWM_UPDATE_REGS;
extern UINT UWM_AUTO_IN_INIT;
extern UINT UWM_AUTO_IN_GENERATE;
extern UINT UWM_AUTO_IN_SEND;
extern UINT UWM_AUTO_IN_GO;
extern UINT UWM_AUTO_IN_PKTEND;
extern UINT UWM_AUTO_OUT_INIT;
extern UINT UWM_AUTO_OUT_GETSTATE;
extern UINT UWM_AUTO_OUT_GO;
extern UINT UWM_AUTO_INPUT;
extern UINT UWM_AUTO_OUTPUT;

// These are all obsolete
//extern UINT UWM_GO_OUT_SET;
//extern UINT UWM_GO_IN_SET;
//extern UINT UWM_IE_IN_SET;
//extern UINT UWM_IE_OUT_SET;
//extern UINT UWM_IACK_OUT_SET;
//extern UINT UWM_IACK_IN_SET;
//extern UINT UWM_RST_OUT_SET;
//extern UINT UWM_RST_IN_SET;
